# Generated by Django 4.1.4 on 2022-12-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_testimonial_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
