# Generated by Django 4.1.4 on 2022-12-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_recent_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recent_post',
            old_name='image',
            new_name='picture',
        ),
    ]
