# Generated by Django 4.1.4 on 2022-12-19 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_rename_image_recent_post_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent_post',
            name='picture',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='Resentpost_pictures')),
                ('recent_post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Main.recent_post')),
            ],
        ),
    ]
