# Generated by Django 4.1.4 on 2022-12-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_remove_recent_post_picture_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
