# Generated by Django 4.1.4 on 2023-01-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0012_delete_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="recent_post",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to="Resentpost_pictures"
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to="Destination_pictures"
            ),
        ),
    ]
